spring:
  datasource:
    url: jdbc:postgresql://project-board-chang-db.internal:5432/postgres
    username: postgres
    password: EOTw02EVGpi9XrV
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.WeblogicJtaPlatform
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true
